### PR TITLE
Brace style change proposal

### PR DESCRIPTION
**Pull request by derekchinn**
http://eslint.org/docs/rules/brace-style#stroustrup

### CODE REVIEW

**Comment by dannify** [comment]
debating this change
````
if (foo) {
  bar();
}
else {
  baz();
}
````
is a problem for me

**Comment by dannify** [comment]
I prefer one true brace style

**Comment by ross-pfahler** [comment]
i think im going to agree with danni here.

**Comment by markdoten** [comment]
Agree with @dannify and @ross-pfahler

**Pull request closed without merging**
